modLoader = "javafml"
loaderVersion = "[48,)"
issueTrackerURL = "https://github.com/FionaTheMortal/better-biome-blend/issues"
license = "LGPL"

[[mods]]
modId = "betterbiomeblend"
version = "${version}"
displayName = "Better Biome Blend"
authors = "FionaTheMortal"
description = "    This mod increases the biome color blending radius and replaces the original blending algorithm with a more efficient one."
#logoFile = ""

[[dependencies.betterbiomeblend]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterbiomeblend]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"
